name: AiPacketClassifier
channels:
  - huggingface
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - boto3=1.24.28
  - botocore=1.27.59
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - filelock=3.9.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipython=8.12.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=0.10.0
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.25.0
  - numpy-base=1.25.0
  - openpyxl=3.0.10
  - openssl=3.0.9
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - pytorch=2.0.1
  - pytz=2022.7
  - readline=8.2
  - regex=2022.7.9
  - requests=2.29.0
  - s3transfer=0.6.0
  - sacremoses=master
  - scapy=2.4.3
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xlsxwriter=3.1.1
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.21.0
      - fsspec==2023.6.0
      - huggingface-hub==0.16.4
      - psutil==5.9.5
      - pyyaml==6.0
      - safetensors==0.3.1
      - sentencepiece==0.1.99
      - tokenizers==0.13.3
      - transformers==4.30.2
accelerate
fsspec
huggingface-hub
psutil
pyyaml
safetensors
sentencepiece
tokenizers
transformers
