name: AiPacketClassifier
channels:
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - appnope=0.1.2
  - arrow-cpp=11.0.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=22.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - blas=1.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - datasets=2.12.0
  - decorator=5.1.1
  - dill=0.3.6
  - executing=0.8.3
  - filelock=3.9.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - future=0.18.3
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - grpc-cpp=1.46.1
  - huggingface_hub=0.15.1
  - icu=58.2
  - idna=3.4
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipython=8.12.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.1.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.3
  - libiconv=1.16
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - multiprocess=0.70.14
  - munkres=1.1.4
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=1.1.1u
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.5
  - python-dateutil=2.8.2
  - python-xxhash=2.0.2
  - pytorch=1.10.2
  - pytz=2022.7
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.29.0
  - responses=0.13.3
  - sacremoses=0.0.43
  - scapy=2.4.3
  - setuptools=67.8.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tokenizers=0.13.2
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - transformers=4.29.2
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xxhash=0.8.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5

