name: classifier
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - cffi=1.15.1
  - contourpy=1.0.5
  - cryptography=41.0.1
  - cycler=0.11.0
  - dbus=1.13.18
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.4.9
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - intel-openmp=2023.1.0
  - ipython=8.12.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.35
  - nss=3.89.1
  - numpy-base=1.25.0
  - openssl=3.0.9
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.1.2
  - ply=3.11
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.11.3
  - python-dateutil=2.8.2
  - pytorch=2.0.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - scapy=2.4.3
  - setuptools=67.8.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.6.3
  - tzdata=2023c
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - certifi==2023.5.7
      - charset-normalizer==3.2.0
      - filelock==3.12.2
      - fsspec==2023.6.0
      - huggingface-hub==0.16.4
      - idna==3.4
      - mypy-extensions==1.0.0
      - numpy==1.25.1
      - packaging==23.1
      - protobuf==3.19.0
      - pyre-extensions==0.0.29
      - pyyaml==6.0
      - regex==2023.6.3
      - requests==2.31.0
      - safetensors==0.3.1
      - sentencepiece==0.1.99
      - tokenizers==0.13.3
      - tqdm==4.65.0
      - transformers==4.30.2
      - typing-extensions==4.7.1
      - typing-inspect==0.9.0
      - urllib3==2.0.3
      - xformers==0.0.20
certifi
charset-normalizer
filelock
fsspec
huggingface-hub
idna
mypy-extensions
numpy
packaging
protobuf
pyre-extensions
pyyaml
regex
requests
safetensors
sentencepiece
tokenizers
tqdm
transformers
typing-extensions
typing-inspect
urllib3
xformers
